import Anthropic from '@anthropic-ai/sdk';
import { NextResponse } from 'next/server';

const IS_DEMO = !process.env.ANTHROPIC_API_KEY;

interface EntryData {
  created_at: string;
  body_locations?: string[];
  pain_type?: string;
  severity?: number;
  triggers?: string[];
  is_chronic?: boolean;
  raw_text?: string;
}

function mockReport(entries: EntryData[]) {
  const first = entries[0];
  const last = entries[entries.length - 1];
  const severities = entries.filter(e => e.severity).map(e => e.severity!);
  const avgSeverity = severities.length ? (severities.reduce((a, b) => a + b, 0) / severities.length).toFixed(1) : 'N/A';

  const locations = new Set<string>();
  const triggers = new Set<string>();
  entries.forEach(e => {
    e.body_locations?.forEach(l => locations.add(l));
    e.triggers?.forEach(t => triggers.add(t));
  });

  const chronological = entries.map(e =>
    `  ${new Date(e.created_at).toLocaleDateString()} — ${e.body_locations?.join(', ') || 'General'} | ${e.pain_type || 'Unspecified'} | Severity: ${e.severity || 'N/R'}/10 | "${e.raw_text || 'Quick-logged'}"`
  ).join('\n');

  return `PATIENT SYMPTOM REPORT
=======================

1. REPORT PERIOD
   ${new Date(first.created_at).toLocaleDateString()} — ${new Date(last.created_at).toLocaleDateString()}

2. SYMPTOM SUMMARY
   Total entries: ${entries.length}
   Severity range: ${Math.min(...severities)}–${Math.max(...severities)}/10
   Average severity: ${avgSeverity}/10
   Affected areas: ${[...locations].join(', ') || 'None specified'}
   Reported triggers: ${[...triggers].join(', ') || 'None noted'}

3. DETAILED CHRONOLOGICAL LOG
${chronological}

4. PATTERNS & TRIGGERS OBSERVED
   - Most affected areas: ${[...locations].slice(0, 3).join(', ')}
   - Common triggers: ${[...triggers].slice(0, 3).join(', ') || 'None consistently reported'}
   - Chronic symptoms reported: ${entries.some(e => e.is_chronic) ? 'Yes' : 'No'}

5. PATIENT'S OWN DESCRIPTIONS
${entries.filter(e => e.raw_text && e.raw_text !== 'Feeling OK').slice(0, 5).map(e => `   "${e.raw_text}"`).join('\n')}

---
This report was auto-generated from patient-logged symptom data. It does not contain any diagnoses or medical assessments.

[DEMO MODE — In production, this report would be generated by Claude AI with richer analysis and formatting.]`;
}

export async function POST(request: Request) {
  try {
    const { entries } = await request.json();
    if (!entries?.length) {
      return NextResponse.json({ error: 'No entries provided' }, { status: 400 });
    }

    if (IS_DEMO) {
      return NextResponse.json({ report: mockReport(entries) });
    }

    const client = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY,
    });

    const entriesSummary = entries.map((e: EntryData) => (
      `Date: ${new Date(e.created_at).toLocaleDateString()}
Location: ${e.body_locations?.join(', ') || 'Not specified'}
Type: ${e.pain_type || 'Not specified'}
Severity: ${e.severity || 'Not rated'}/10
Triggers: ${e.triggers?.join(', ') || 'None noted'}
Chronic: ${e.is_chronic ? 'Yes' : 'No'}
Patient's words: "${e.raw_text || 'Quick-logged'}"
---`
    )).join('\n');

    const message = await client.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 2048,
      system: `You are generating a doctor-ready symptom report for a patient's healthcare provider.

CRITICAL RULES:
- NEVER include any diagnosis or suspected conditions
- NEVER give medical advice or treatment recommendations
- ONLY organize and summarize the symptom data the patient logged
- Use professional, clinical language appropriate for a doctor's office
- Include dates, patterns, severity trends, and the patient's own descriptions
- Organize chronologically and by body system

Format the report as a clean, professional document with sections:
1. Report Period
2. Symptom Summary (overview of frequency, locations, severity range)
3. Detailed Chronological Log
4. Patterns & Triggers Observed
5. Patient's Own Descriptions (notable quotes)

End with: "This report was auto-generated from patient-logged symptom data. It does not contain any diagnoses or medical assessments."`,
      messages: [
        {
          role: 'user',
          content: `Generate a doctor report from these symptom entries:\n\n${entriesSummary}`,
        },
      ],
    });

    const content = message.content[0];
    if (content.type !== 'text') {
      return NextResponse.json({ error: 'Unexpected response' }, { status: 500 });
    }

    return NextResponse.json({ report: content.text });
  } catch (err) {
    console.error('Doctor report error:', err);
    return NextResponse.json(
      { error: 'Failed to generate report. Please try again.' },
      { status: 500 }
    );
  }
}
